# Generated by Django 3.1 on 2020-08-20 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('isChild', models.BooleanField(default=False)),
                ('attending_ceremony', models.BooleanField(default=False)),
                ('attending_cocktail', models.BooleanField(default=False)),
                ('attending_dinner', models.BooleanField(default=False)),
                ('attending_brunch', models.BooleanField(default=False)),
                ('invited_ceremony', models.BooleanField(default=True)),
                ('invited_cocktail', models.BooleanField(default=True)),
                ('invited_dinner', models.BooleanField(default=True)),
                ('invited_brunch', models.BooleanField(default=True)),
                ('party', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='guest.party')),
            ],
        ),
    ]
