# Generated by Django 3.1 on 2020-08-20 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='isChild',
            new_name='is_Child',
        ),
    ]
