# Generated by Django 3.1 on 2020-08-20 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_auto_20200820_0554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='is_Child',
            new_name='is_child',
        ),
    ]
