# Generated by Django 3.1 on 2020-08-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0003_auto_20200820_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
