# Generated by Django 3.1 on 2020-09-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0004_guest_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='attending_ceremony',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='invited_brunch',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='invited_ceremony',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='invited_cocktail',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='invited_dinner',
        ),
        migrations.AddField(
            model_name='party',
            name='invitation_number',
            field=models.CharField(default='aaaa', max_length=6, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='party',
            name='invitation_opened',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
