# Generated by Django 3.1.1 on 2020-09-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0005_auto_20200901_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='comment',
        ),
        migrations.AddField(
            model_name='party',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
