# Generated by Django 3.1 on 2020-09-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0006_auto_20200906_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='invited_brunch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='party',
            name='invited_dinner',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
