# Generated by Django 3.1 on 2020-09-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0007_auto_20200910_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='response_received',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
